parser: babel-eslint
extends:
  - airbnb
  - plugin:flowtype/recommended
  - plugin:import/errors
  - plugin:import/warnings
plugins:
  - flowtype
  - import
env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    experimentalObjectRestSpread: true
rules:
  no-unused-expressions: off
  semi:
    - error
    - always
    - omitLastInOneLineBlock: true
