// flow-typed signature: 2bda91eb780e435a04872ff747b3be38
// flow-typed version: <<STUB>>/pug_v^2.0.0-beta6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug/development' {
  declare module.exports: any;
}

declare module 'pug/lib/index' {
  declare module.exports: any;
}

declare module 'pug/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug/development.js' {
  declare module.exports: $Exports<'pug/development'>;
}
declare module 'pug/lib/index.js' {
  declare module.exports: $Exports<'pug/lib/index'>;
}
declare module 'pug/register.js' {
  declare module.exports: $Exports<'pug/register'>;
}
